---


#- name: deploy registry server
#  command: "docker run -d -p 5000:5000 --restart=always --name registry -v /DOCKER_SHARE/var/lib/registry:/var/lib/registry registry:2"

- name: Creates registry root directory
  file: path=/var/lib/registry state=directory

- name: docker registry container
  docker:
    name: docker_registry_con_01
    image: registry:2
    state: restarted
    ports:
    - "5000:5000"
    env:
       REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
    -  /DOCKER_SHARE
