---

- name: uname_r
  command: uname -r
  register: uname_r_value

- debug: msg={{ uname_r_value.stdout }}

- name: install docker dependencies...
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - lxc
    - iptables

- apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80  id=58118E89F3A912897C070ADBF76221572C52609D
- file: path=/etc/apt/sources.list.d/docker.list state=touch
- name: configure OS
  lineinfile: dest=/etc/apt/sources.list.d/docker.list regexp="^deb" line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"

#  THIS VERSION IS FOR UBUNTU 16.04[LTS]
#- name: configure OS
#  lineinfile: dest=/etc/apt/sources.list.d/docker.list regexp="^deb" line="deb deb https://apt.dockerproject.org/repo ubuntu-xenial main"

- apt: update_cache=yes
#- apt: purge=true

- name: Install pip
  easy_install:
      name=pip

- name: Install docker-py
  pip:
      name=docker-py

- debug: msg=install linux-image-extra-{{ uname_r_value.stdout }}
- name: install linux-image-extra-{{ uname_r_value.stdout }}
  apt: name=linux-image-extra-{{ uname_r_value.stdout }} state=installed update_cache=yes

- apt: update_cache=yes

- name: install docker engine
  apt: name=docker-engine state=installed update_cache=yes


- file: path=/etc/default/docker state=touch

- name: configure proxy to docker
  lineinfile: dest=/etc/default/docker regexp="^export http_proxy=" line="export http_proxy={{http_proxy}}/"
  when: http_proxy is defined

- name: configure proxy ssl to docker
  lineinfile: dest=/etc/default/docker regexp="^export https_proxy=" line="export https_proxy={{http_proxy}}/"
  when: http_proxy is defined

- name: configure proxy ssl to docker
  lineinfile: dest=/etc/default/docker regexp=^DOCKER_OPTS= line=DOCKER_OPTS="--insecure-registry {{ansible_hostname}}.{{ansible_domain}}:5000"
  when: http_proxy is defined

- service: name=docker state=restarted